
# Ejercicio final: Extraer información de un archivo JSON usando expresiones regulares (regex)


## Objetivo:

El objetivo de este ejercicio es practicar la utilización de expresiones regulares (regex) para extraer información específica de un archivo JSON. El ejercicio se enfocará en la lectura y análisis de un archivo JSON que contiene información sobre clientes.

## Descripción:

### Obtener el archivo JSON:
Lea archivo JSON 'clientes.json' que contiene la información sobre clientes. El archivo debe tener una estructura similar a la siguiente:

In [5]:
{
  "clientes": [
    {
      "nombre": "Juan Pérez",
      "direccion": "Calle Mayor 123",
      "ciudad": "San José",
      "telefono": "+506 2222-3333"
    },
    {
      "nombre": "María Gómez",
      "direccion": "Avenida Central 456",
      "ciudad": "Alajuela",
      "telefono": "+506 8888-4444"
    },
    {
      "nombre": "Pedro Ramírez",
      "direccion": "Barrio Escalante 789",
      "ciudad": "Heredia",
      "telefono": "+506 5555-6666"
    },
    {
      "nombre": "Ana Castro",
      "direccion": "Avenida 10 Calle 5",
      "ciudad": "Cartago",
      "telefono": "+506 3333-4444"
    },
    {
      "nombre": "Carlos Jiménez",
      "direccion": "Calle Principal 12",
      "ciudad": "Liberia",
      "telefono": "+506 6666-7777"
    },
    {
      "nombre": "Diana Solano",
      "direccion": "Barrio La Unión 78",
      "ciudad": "Puntarenas",
      "telefono": "+506 9999-8888"
    }
  ]
}

{'clientes': [{'nombre': 'Juan Pérez',
   'direccion': 'Calle Mayor 123',
   'ciudad': 'San José',
   'telefono': '+506 2222-3333'},
  {'nombre': 'María Gómez',
   'direccion': 'Avenida Central 456',
   'ciudad': 'Alajuela',
   'telefono': '+506 8888-4444'},
  {'nombre': 'Pedro Ramírez',
   'direccion': 'Barrio Escalante 789',
   'ciudad': 'Heredia',
   'telefono': '+506 5555-6666'},
  {'nombre': 'Ana Castro',
   'direccion': 'Avenida 10 Calle 5',
   'ciudad': 'Cartago',
   'telefono': '+506 3333-4444'},
  {'nombre': 'Carlos Jiménez',
   'direccion': 'Calle Principal 12',
   'ciudad': 'Liberia',
   'telefono': '+506 6666-7777'},
  {'nombre': 'Diana Solano',
   'direccion': 'Barrio La Unión 78',
   'ciudad': 'Puntarenas',
   'telefono': '+506 9999-8888'}]}

##

## Extraer información usando regex:
### Utilice expresiones regulares para extraer la siguiente información de cada cliente:
- Nombre completo: Juan Pérez, María Gómez, Pedro Ramírez
- Dirección completa: Calle Mayor 123, Avenida Central 456, Barrio Escalante 789
- Ciudad: San José, Alajuela, Heredia
- Número de teléfono: +506 2222-3333, +506 8888-4444, +506 5555-6666

### Imprima la información extraída para cada cliente en un formato claro y organizado.


## Pistas:

- Utilice la librería re de Python para trabajar con expresiones regulares.
- Defina patrones de expresión regular específicos para cada tipo de información que desea extraer.
- Recorra el archivo JSON y aplique los patrones regex a cada cliente.
- Utilize métodos como findall() o search() para encontrar las coincidencias en el texto.

In [6]:
import json
import re

# Cargar el archivo JSON
try:
    with open("clientes.json", "r", encoding="utf-8") as archivo:
        datos_clientes = json.load(archivo)
except FileNotFoundError as e:
    print(f"Error: El archivo JSON 'clientes.json' no se encontró.")
except json.JSONDecodeError as e:
    print(f"Error al decodificar el archivo JSON: {e}")
except Exception as e:
    print(f"Error inesperado: {e}")
    datos_clientes = []
    
patron_nombre = r"[A-Z][a-z]+ [A-Z][a-z]+"  # Coincide con "Nombre Apellido"
patron_direccion = r"[A-Za-z]+ [A-Za-z]* \d+"  # Coincide con "Calle Número"
patron_ciudad = r"[A-Z][a-z]+"  # Coincide con "Ciudad"
patron_telefono = r"\+\d{3} \d{4}-\d{4}"  # Coincide con "+506 XXXX-XXXX"

# Definir patrones de regex
for cliente in datos_clientes:
    texto = cliente.get("cliente", "")
    
nombre = re.search(patron_nombre, texto).group()
direccion = re.search(patron_direccion, texto).group()
ciudad = re.search(patron_ciudad, texto).group()
telefono = re.search(patron_telefono, texto).group()

nombre = nombre_match.group() if nombre_match else "No encontrado"
direccion = direccion_match.group() if direccion_match else "No encontrado"
ciudad = ciudad_match.group() if ciudad_match else "No encontrado"
telefono = telefono_match.group() if telefono_match else "No encontrado"

AttributeError: 'str' object has no attribute 'get'

## Solucion con ayuda ##

In [9]:
import json
import re

# Cargar el archivo JSON
try:
    with open("clientes.json", "r", encoding="utf-8") as archivo:
        datos_clientes = json.load(archivo)
except FileNotFoundError:
    print("Error: El archivo JSON 'clientes.json' no se encontró.")
    datos_clientes = []
except json.JSONDecodeError as e:
    print(f"Error al decodificar el archivo JSON: {e}")
    datos_clientes = []
except Exception as e:
    print(f"Error inesperado: {e}")
    datos_clientes = []

# Definir patrones de regex
patron_nombre = r"[A-Z][a-z]+\s[A-Z][a-z]+"
patron_direccion = r"[A-Za-z]+\s[A-Za-z]*\s\d+"
patron_ciudad = r"(San José|Alajuela|Heredia)"
patron_telefono = r"\+\d{3}\s\d{4}-\d{4}"

# Procesar clientes
for cliente in datos_clientes:
    texto = cliente if isinstance(cliente, str) else cliente.get("cliente", "")
    
    nombre_match = re.search(patron_nombre, texto)
    direccion_match = re.search(patron_direccion, texto)
    ciudad_match = re.search(patron_ciudad, texto)
    telefono_match = re.search(patron_telefono, texto)
    
    nombre = nombre_match.group() if nombre_match else "No encontrado"
    direccion = direccion_match.group() if direccion_match else "No encontrada"
    ciudad = ciudad_match.group() if ciudad_match else "No encontrada"
    telefono = telefono_match.group() if telefono_match else "No encontrado"
    
    print("\nCliente:")
    print(f"Nombre: {nombre}")
    print(f"Dirección: {direccion}")
    print(f"Ciudad: {ciudad}")
    print(f"Teléfono: {telefono}")


Cliente:
Nombre: No encontrado
Dirección: No encontrada
Ciudad: No encontrada
Teléfono: No encontrado
